[project]
name = "ArkStudio"
version = "0.1.0"
description = "Arknights Assets Studio"
authors = [
    { name = "Harry Huang", email = "harryhuang2652@qq.com" }
]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "flatbuffers (~=24.3)",
    "numpy (~=1.26)",
    "Pillow (~=9.5)",
    "UnityPy (~=1.22)",
    "customtkinter (~=5.2)",
    "requests (~=2.32)",
    "simpleaudio-patched (~=1.0)"
]

[tool.poetry]
package-mode = false

[[tool.poetry.source]]
name = "PyPI-Tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pyinstaller = "6.12.0"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
